/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VVIPPartnerId = bigint;
export interface VVIPPartnerProfile {
  'principal' : Principal,
  'businessName' : string,
  'fullName' : string,
  'isActive' : boolean,
  'phone' : string,
  'registrationTime' : Time,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllVVIPPartners' : ActorMethod<[], Array<VVIPPartnerProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGreeting' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVVIPPartnerProfile' : ActorMethod<[], [] | [VVIPPartnerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isVVIPPartner' : ActorMethod<[], boolean>,
  'registerVVIPPartner' : ActorMethod<[string, string, string], VVIPPartnerId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];